/* AY7E 32-bit shift-register PRNG, native 08034580..08034604.
 * Unsigned wrap and byte truncation are intentional. Semantic C only. */
#include <stdint.h>
extern uint32_t gRandomState; /* 020237CC */
/* 08034580 */ void InitializeRandom(void) { gRandomState=1; }
/* 080345E4 */
uint8_t NextRandomBit(void)
{
    uint8_t bit=gRandomState>>31;
    if(bit)gRandomState=((gRandomState^0x10000u)<<1)|1u;
    else gRandomState<<=1;
    return bit;
}
/* 0803458C */
uint8_t NextRandomByte(void)
{
    uint8_t n=0;for(unsigned i=0;i<8;++i)n=(uint8_t)((n<<1)|NextRandomBit());return n;
}
/* 080345B4 uses signed remainder, even for reversed bounds. The native
 * divide-by-zero handler 08039328 returns immediately, remainder zero. */
uint32_t RandomByteInclusive(uint32_t minimum,uint32_t maximum)
{
    minimum&=255;maximum&=255;
    if(minimum!=maximum) {
        uint8_t n=NextRandomByte();int32_t span=(int32_t)maximum-(int32_t)minimum+1;
        minimum=(minimum+(span?(int32_t)n%span:0))&255;
    }
    return minimum;
}
/* 0803460C: first generated byte is the high byte. */
uint16_t NextRandomHalfword(void)
{
    uint16_t high=NextRandomByte();
    return (uint16_t)((high<<8)|NextRandomByte());
}
/* 08034628 consumes two bytes even when the bounds are equal. */
uint16_t RandomHalfwordInclusive(uint16_t minimum,uint16_t maximum)
{
    uint16_t n=NextRandomHalfword();
    int32_t span=(int32_t)maximum-minimum+1;
    return (uint16_t)(minimum+(span?(int32_t)n%span:0));
}
